# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./dboard-client/package.json ./
COPY ./dboard-client/package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.0 -g --silent
RUN npm install react-app-rewired@2.1.6 -g --silent
RUN npm install pm2 -g
COPY ./dboard-client ./
RUN pm2 start cors-anywhere.js
RUN npm run start
